#
# from enum import Enum
#
#
# class ParticipantStatus(Enum):
#
#     PARTICIPANT_NOT_INVITED_YET = 0
#     PARTICIPANT_INVITED = 1
#     PARTICIPANT_JOINED = 2
#     PARTICIPANT_DECLINED = 3
#     PARTICIPANT_LEFT = 4
#     PARTICIPANT_FINISHED = 5
#     PARTICIPANT_UNRESPONSIVE = 6


from Enum import enum as enum

ParticipantStatus= enum(PARTICIPANT_NOT_INVITED_YET='PARTICIPANT_NOT_INVITED_YET',
                   PARTICIPANT_INVITED='PARTICIPANT_INVITED',
                   PARTICIPANT_JOINED='PARTICIPANT_JOINED',
                   PARTICIPANT_DECLINED='PARTICIPANT_DECLINED',
                   PARTICIPANT_LEFT='PARTICIPANT_LEFT',
                   PARTICIPANT_FINISHED='PARTICIPANT_FINISHED',
                   PARTICIPANT_UNRESPONSIVE='PARTICIPANT_UNRESPONSIVE')
